apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/Users/zihua/.kube/admin.conf"
profiles:
- schedulerName: fixednode
  plugins:
    filter:
      enabled:
        - name: fixednode
    postBind:
      enabled:
        - name: fixednode
